/** @type {import('next').NextConfig} */
module.exports = {
  // Optional: enable static export output if you want `out/` to be generated by `next build`.
  // If you prefer Vercel's serverless Next.js, you can remove this option.
  output: 'export',
}
